# Generated by Django 5.1.5 on 2025-02-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='url',
            field=models.URLField(blank=True, default=models.CharField(max_length=200)),
        ),
    ]
