# Generated by Django 5.1.5 on 2025-02-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tasks_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='url',
            field=models.CharField(default='task/', max_length=50),
        ),
    ]
