# Generated by Django 5.1.5 on 2025-02-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('class_name', models.CharField(choices=[('11th', '11th'), ('12th', '12th')], max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
